let playList= {
        "chinese":[ 
            ["光年之外" , "T4SimnaiktU"],
            ["太陽" , "7vlVjfMl_Nk"],
            ["少年" , "uIcwucqswaI"],
            ["怎麼了" , "376Z3gHh6kQ"],
            ["想見你想見你想見你" , "6bZpnskdmQ4"],
            ["派對動物" , "kYSgsDzX218"],
            ["稻香" , "sHD_z90ZKV0"],
            ["野狼Disco" , "ipggaw0mGjk"],
            ["讓我留在你身邊" , "4iVW7OhZ0p8"],
            ["飄向北方" , "qIF8xvSA0Gw"],
            ["那女孩對我說" , "A8N_sQ_kK48"],
            ["歐若拉" , "vWcVQZ-NQsg"],
            ["你的答案" , "-rt_8FOLydg"],
            ["真的傻" , "aHNsuYHlMQM"],
            ["天真有邪" , "hrdQ_6K6oXk"],
            ["月夜" , "yUL6kxtocfk"],
            ["煙幕" , "P8uJ4gFjJGE"],
            ["起風了" , "vV50fYfv3HI"],
            ["囂張" , "oAUmNEUJlJ0"],
            ["到此為止" , "T7IK_5XCRiU"],
            ["不該" , "_VxLOj3TB5k"],
            ["綠色" , "WY6nQK7zbsk"],
            ["無名之輩" , "esYjbyBm8zw"],
            ["不染" , "vqbh0h6kquQ"],
            ["紅色高跟鞋" , "WpHY9ZHZRQs"],
            ["玫瑰少年" , "s0woEEoRyko"],
            ["達拉崩吧" , "6evIBFNwPWI"],
            ["鬥牛" , "EjmqAvhVglM"],
            ["你一定要幸福" , "hLThkxsnQpk"],
            ["後來遇見他" , "aVfZMroXqqY"],
            ["獨家記憶" , "xDUeXJjX9RU"],
            ["追光者" , "5DKNU34L5DA"],
            ["一笑傾城" , "dCqqqyeZGjM"],
            ["摩天動物園" , "MywiD2o5tTw"],
            ["再見煙火" , "yjWwfDW9IoA"],
            ["走心" , "EptAOgshrQ8"],
            ["我好想你" , "P_pyfLArjQg"],
            ["走著走著就散了" , "mgkkobzQSlU"],
            ["洋蔥" , "6Duo89XuYIM"],
            ["青春修練手冊" , "SA7o4c8lxdk"],
            ["與我無關" , "8tuzFSXeKI0"],
            ["逆戰" , "gY5Wiri9q8U"],
            ["他不懂" , "pmzmycNDP4c"],
            ["為你而戰" , "L1JgSJ7M_Lk"],
            ["不用去猜" , "AlIEogRBK_I"],
            ["SHEEP (羊)" , "-qSzP9aReOA"],
            ["可樂" , "mp6E_avCnXc"],
            ["勇氣" , "b-XPRDSFC-M"],
            ["心引力" , "-oHYFBE8bgk"],
            ["驚雷" , "uDtIIu8okUU"],
            ["懸日","Nf1C1fSJG_8"],
            ["你的酒館對我打了烊","ynaARgs_yvQ"],
            ["來自天堂的魔鬼","FWtbGkpdoP4"],
            ["失眠飛行","a4eR-5OJ-7Q"],
            ["來個蹦蹦","R2V9sHAlLuQ"],
            ["我很快樂","Ezd_DLawfHI"],
            ["多想在平庸的生活擁抱你","kAP_x0krk7A"],
            ["你啊你啊","saiJbqHBuew"],
            ["紙短情長","FuDdstaZXdw"],               
        ],
        "korea":[
            ["AnySong" , "UuV2BmJ1p_I"],
            ["Blueming" , "D1PvIWdJ8xo"],
            ["Candy" , "gmgcRWxhmqY"],
            ["FIESTA" , "mbdArlIBPHk"],
            ["Happy" , "Raj-AuQgCTg"],
            ["OhMyGod" , "om3n2ni8luE"],
            ["Psycho" , "uR8Mrt1IpXg"],
            ["Snapping" , "deV_DmHKwjc"],
            ["WANNABE" , "fE2h3lGlOsk"],
            ["gogobebe" , "Oao3j2hUVvE"],
            ["Some" , "jHkxauiiEWs"],
            ["Obsession" , "uxmP4b2a0uY"],
            ["Cherry Bomb" , "LZTxwIuNDSQ"],
            ["Energetic" , "kfNdEjQl0T0"],
            ["NOT BY THE MOON" , "ladClnnJhqg"],
            ["Shine","Nu2yQ1zYDYU"],
            ["BBIBBI","nM0xDI5R50E"],
            ["PARTY","meDhOybc4Yo"],
            ["LOVE ME RIGHT","BDfL-CNzcuY"],
            ["Oasis","cmJRVOtvKdI"],
            ["GRAVITY","prFir9hRSxU"],
            ["What a life","AtNBhPxVwh0"],
            ["Make Me Love You","TVUqLBRQom8"],
            ["Blooming Day","UdjEoGzXxmI"],
            ["The One","4KprfCxyoTo"],
            ["Ridin","vofjeJvRT9c"],
            ["GO","5AEYijM9zPM"],
            ["Dumhdurum","WqzTRK5GPWQ"],
            ["Good Guy","n8zQysKciao"],
            ["on","aQO0cat45Ys"],
            ["HIP","KhTeiaCezwM"],
            ["LION","6oanIo_2Z4Q"],
            ["FLASH","LlQEKB2H7z4"],
            ["Chocolate","-sKqPjhSiq0"],
            ["MORE & MORE","mH0_XpSHkZo"],
            ["SUPER Clap","QNQW_lKji5A"],
            ["4 Walls","bUy3OKrl-pI"],
            ["She is","jmNhfjzmMrU"],
            ["Good Evening","7dGwk5-QMpc"],
            ["UN Village","-EfjXQgE1e8"],
            ["WANT","-OfOkiVFmhM"],
            ["Woman","kVTOkvJjCv0"],
            ["Peek-A-Boo","6uJf2IT2Zh8"],
            ["Sign","ig1D5DVP5MY"],
            ["Hellevator","O2_snIiKBYE"],
            ["HIT","F9CrRG6j2SM"],
            ["Kill This Love","2S24-y0Ij3Y"],
            ["Adios","r0lA20n9Q6U"],
            ["DDD","axVvZrDz60k"],
            ["SHAKE IT","r-QXlHzYheg"],
            ["FANTASIA","p2JzPlpA1Iw"],
            ["PUNCH","U08OSl3V4po"],   
            ["Yours","N2dsnGc7TFk"],
            ["Nonstop","iDjQSdN_ig8"],  
            ["Stay Tonight","YPFIh0dfYfw"],
            ["Spit it out","V8FXWf0s7K0"],
            ["Let's Love","Ygrv55VRRas"],
            ["DUN DUN","NoYKBAajoyo"],
            ["DAZZLE DAZZLE","RTeOt6n90vM"],
            ["kick it","2OvyA2__Eas"], 
            ["교차로 (Crossroads)","kx5TWKPE5sU"],
            ["knock","Zz7YZtpz2Ek"],
            ["FANCY","kOHB85vDuow"],
            ["Bomb Bomb","Y44vb5I3OAU"],
            ["DALLA DALLA","pNfTK39k55U"],
            ["Violeta","Z8_aiEDLoY4"],
            ["Eung Eung","499YUeNoYVE"],
            ["wolf","cyiMFg_a50s"],
            ["ko ko bop","4Q5zzRriFyU"]
        ]
   
};
//播放起訖秒數
let playTime = [75,85];
let topic =[
    "中文歌曲",
    "韓文歌曲",
    "西洋歌曲"
];
let sound=[
    "guess-game/win.mp3",
    "guess-game/lose.mp3"
]